version: '3'
services:
  cassandra:
    hostname: cassandra-host
    image: cassandra:3
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    volumes: # uncomment if you desire mounts, also uncomment cluster.sh
    - ./data/cassandra-1:/var/lib/cassandra:rw
  cassandra-client:
    hostname: cassandra-client
    links:
      - "cassandra:db"
    image: cassandra:3
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && sleep infinity"
    #command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    volumes: # uncomment if you desire mounts, also uncomment cluster.sh
      - ./scripts:/home:rw