version: '3'
services:
  fortis:
    build: .
    env_file: .env
    links:
      - "cassandra:db"
    tty: true
    command: /bin/bash
  cassandra:
    hostname: cassandra-host #why?
    image: cassandra:3 
    tty: true
    command: /docker-entrypoint.sh cassandra -f
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
  cassandra-client:
    hostname: cassandra-client #why?
    image: cassandra:3
    depends_on:
      - cassandra
    volumes: # uncomment if you desire mounts, also uncomment cluster.sh
      - ./scripts:/home:rw
    tty: true
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && ./home/setupCassandra.sh && sleep infinity"
