version: '3'
services:

######## CASSANDRA ########
  cassandra-node1:
    image: cassandra:3
    environment:
      WAIT_TIMEOUT: "60"
      JVM_OPTS: "-Dcassandra.consistent.rangemovement=false"
      CASSANDRA_CLUSTER_NAME: "DemoCluster"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_DC: "DATA"
    restart: always 
    expose:
      - 9042
  cassandra-init:
    image: cassandra:3
    volumes:
      - ./compose-resources/cassandra:/init/scripts
    command: /init/scripts/cassandra-init.sh
    links:
      - cassandra-node1:cassandra
    depends_on:
      - cassandra-node1
    restart: on-failure
    stdin_open: true
    tty: true

######## SPARK ########
  # Expose ports for monitoring.
  # SparkContext web UI on 4040 -- only available for the duration of the application.
  # Spark master’s web UI on 8080.
  # Spark worker web UI on 8081.
  fortis-master:
    build: .
    env_file: .env
    expose:
      - 4040 
      - 8080
      - 8081
    links:
      - cassandra-node1:cassandra
    volumes:
      - ./compose-resources/spark:/init/scripts
      - ./data/fortis-master:/root:rw
    stdin_open: true
    tty: true
    command: /init/scripts/spark-submit-cmd.sh
    restart: on-failure
